const DEFAULT_EVENTS=[
{id:"historyland-2026",name:"Historyland 2026",date:"2026-08-22",time:"17:00",venue:"Camp Ground 22",regular:1500,vip:3500,status:"เปิดขาย",image:"images/event1.png"},
{id:"delef-fest-2026",name:"DELEF FEST 2026",date:"2026-10-25",time:"18:00",venue:"IMPACT ARENA",regular:1800,vip:4500,status:"เร็ว ๆ นี้",image:"images/event-banner.png"}
];
function events(){const s=localStorage.getItem("delef_events");if(!s){localStorage.setItem("delef_events",JSON.stringify(DEFAULT_EVENTS));return [...DEFAULT_EVENTS]}try{return JSON.parse(s)}catch{return [...DEFAULT_EVENTS]}}
function saveEvents(v){localStorage.setItem("delef_events",JSON.stringify(v))}
function money(n){return Number(n||0).toLocaleString("th-TH")+" บาท"}
function dateTH(v){if(!v)return "-";return new Date(v+"T00:00:00").toLocaleDateString("th-TH",{day:"numeric",month:"short",year:"numeric"})}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function poster(e,cls=""){return e.image?`<img class="${cls}" src="${e.image}" alt="${esc(e.name)}">`:`<div class="poster-fallback ${cls}">${esc(e.name)}</div>`}
function card(e){return `<article class="event-card"><div class="poster">${poster(e)}<span class="badge">${esc(e.status)}</span></div><div class="card-body"><h3>${esc(e.name)}</h3><p><i class="fa-regular fa-calendar"></i>${dateTH(e.date)} · ${esc(e.time)} น.</p><p><i class="fa-solid fa-location-dot"></i>${esc(e.venue)}</p><div class="price">เริ่มต้น ${money(e.regular)}</div><a class="btn red full" href="event.html?id=${encodeURIComponent(e.id)}">ดูรายละเอียด <i class="fa-solid fa-arrow-right"></i></a></div></article>`}
function renderHome(){const el=document.getElementById("homeEvents");if(!el)return;const list=events().filter(e=>e.status==="เปิดขาย");el.innerHTML=list.length?list.map(card).join(""):`<div class="empty">ยังไม่มีงานที่เปิดขาย</div>`}
function renderEvents(){const el=document.getElementById("eventList"),input=document.getElementById("search");if(!el)return;function draw(){const q=(input.value||"").toLowerCase();const list=events().filter(e=>(e.name+" "+e.venue).toLowerCase().includes(q));el.innerHTML=list.length?list.map(card).join(""):`<div class="empty">ไม่พบคอนเสิร์ต</div>`}input.addEventListener("input",draw);draw()}
function getEvent(){const id=new URLSearchParams(location.search).get("id");return events().find(e=>e.id===id)||events()[0]}
function renderDetail(){const el=document.getElementById("detail");if(!el)return;const e=getEvent();if(!e){el.innerHTML="<div class='empty'>ไม่พบงาน</div>";return}el.innerHTML=`<div class="detail"><div class="detail-poster">${poster(e)}</div><div><span class="kicker">${esc(e.status)}</span><h1>${esc(e.name)}</h1><div class="info-line"><i class="fa-regular fa-calendar"></i>${dateTH(e.date)}</div><div class="info-line"><i class="fa-regular fa-clock"></i>${esc(e.time)} น.</div><div class="info-line"><i class="fa-solid fa-location-dot"></i>${esc(e.venue)}</div><h2 class="mt">รายละเอียดงาน</h2><p>เตรียมพบกับประสบการณ์คอนเสิร์ต DELEF FEST ผ่านระบบ GOPASS เลือกประเภทบัตรและเข้าสู่คิวได้จากหน้านี้</p><div class="ticket-types"><div><b>VIP</b><strong>${money(e.vip)}</strong></div><div><b>ธรรมดา (REGULAR)</b><strong>${money(e.regular)}</strong></div></div>${e.status==="เปิดขาย"?`<a class="btn red full" href="queue.html?id=${encodeURIComponent(e.id)}">กดบัตร <i class="fa-solid fa-ticket"></i></a>`:`<button class="btn disabled full" disabled>${esc(e.status)}</button>`}</div></div>`}
function renderSeat(){const el=document.getElementById("seatPage");if(!el)return;const e=getEvent();if(!e)return;let type=localStorage.getItem("ticketType")||"",qty=Number(localStorage.getItem("ticketQty")||1);el.innerHTML=`<div class="select-layout"><section class="zone-box"><div class="section-head"><div><span class="kicker">SELECT ZONE</span><h1>เลือกโซนบัตร</h1><p>${esc(e.name)} · ${dateTH(e.date)}</p></div></div><div class="stage-big">STAGE</div><div class="zone-map"><button class="zone regular-zone" onclick="pickZone('REGULAR',${e.regular})">REGULAR<br><small>${money(e.regular)}</small></button><button class="zone vip-zone" onclick="pickZone('VIP',${e.vip})">VIP<br><small>${money(e.vip)}</small></button></div><div class="legend"><span><i class="dot blue"></i> VIP</span><span><i class="dot red-dot"></i> REGULAR</span></div></section><aside class="order"><h2>สรุปคำสั่งซื้อ</h2><div id="order"><p class="muted">เลือกโซนที่ต้องการ</p></div><label>จำนวนบัตร<select id="qty">${[1,2,3,4].map(n=>`<option ${n===qty?"selected":""}>${n}</option>`).join("")}</select></label><div class="total"><span>รวมทั้งหมด</span><b id="total">0 บาท</b></div><button class="btn red full" onclick="checkout()">ดำเนินการต่อ</button></aside></div>`;window.currentEvent=e;window.selectedType=type;window.selectedPrice=type==="VIP"?e.vip:type==="REGULAR"?e.regular:0;updateOrder();let sec=600;setInterval(()=>{sec--;if(sec<0)sec=0;document.getElementById("timer").textContent=`${String(Math.floor(sec/60)).padStart(2,"0")}:${String(sec%60).padStart(2,"0")}`},1000)}
function pickZone(type,price){window.selectedType=type;window.selectedPrice=price;localStorage.setItem("ticketType",type);updateOrder()}
function updateOrder(){const box=document.getElementById("order");if(!box)return;const q=Number(document.getElementById("qty")?.value||1);const t=window.selectedType||"";box.innerHTML=t?`<div class="order-row"><span>${t}</span><b>${money(window.selectedPrice)}</b></div>`:`<p class="muted">เลือกโซนที่ต้องการ</p>`;document.getElementById("total").textContent=money((window.selectedPrice||0)*q);document.getElementById("qty")?.addEventListener("change",updateOrder,{once:true})}
function checkout(){if(!window.selectedType){alert("กรุณาเลือกโซนก่อน");return}const q=Number(document.getElementById("qty").value);localStorage.setItem("ticketQty",q);localStorage.setItem("ticketPrice",window.selectedPrice);alert("ตัวอย่างระบบ: เลือกบัตรสำเร็จ ขั้นตอนชำระเงินจริงสามารถเชื่อมต่อ Backend ต่อได้");}
function initAdmin(){const rows=document.getElementById("rows"),form=document.getElementById("form"),file=document.getElementById("imageFile"),preview=document.getElementById("preview"),modal=document.getElementById("modal");let editing=null,currentImage="";function draw(){rows.innerHTML=events().map(e=>`<tr><td>${e.image?`<img class="thumb" src="${e.image}">`:"-"}</td><td><b>${esc(e.name)}</b></td><td>${dateTH(e.date)}<br>${esc(e.time)} · ${esc(e.venue)}</td><td>Regular ${money(e.regular)}<br>VIP ${money(e.vip)}</td><td><span class="status">${esc(e.status)}</span></td><td><button class="icon-btn" onclick="editAdmin('${e.id}')"><i class="fa-solid fa-pen"></i></button><button class="icon-btn danger" onclick="deleteAdmin('${e.id}')"><i class="fa-solid fa-trash"></i></button></td></tr>`).join("")}window.openForm=()=>{editing=null;currentImage="";form.reset();preview.classList.add("hide");modal.classList.remove("hide")};window.closeForm=()=>modal.classList.add("hide");window.deleteAdmin=id=>{if(confirm("ลบงานนี้หรือไม่?")){saveEvents(events().filter(e=>e.id!==id));draw()}};window.editAdmin=id=>{const e=events().find(x=>x.id===id);if(!e)return;editing=id;currentImage=e.image||"";form.name.value=e.name;form.date.value=e.date;form.time.value=e.time;form.venue.value=e.venue;form.regular.value=e.regular;form.vip.value=e.vip;form.status.value=e.status;if(currentImage){preview.src=currentImage;preview.classList.remove("hide")}modal.classList.remove("hide")};file.addEventListener("change",()=>{const f=file.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{currentImage=r.result;preview.src=currentImage;preview.classList.remove("hide")};r.readAsDataURL(f)});form.addEventListener("submit",ev=>{ev.preventDefault();const v=events();const item={id:editing||"event-"+Date.now(),name:form.name.value.trim(),date:form.date.value,time:form.time.value,venue:form.venue.value.trim(),regular:Number(form.regular.value),vip:Number(form.vip.value),status:form.status.value,image:currentImage||"images/event1.png"};const idx=v.findIndex(e=>e.id===item.id);if(idx>=0)v[idx]=item;else v.push(item);saveEvents(v);closeForm();draw()});draw()}
function checkout() {
    if (!window.selectedType) {
        alert("กรุณาเลือกโซนก่อน");
        return;
    }

    const q = Number(document.getElementById("qty").value);

    localStorage.setItem("ticketQty", q);
    localStorage.setItem("ticketPrice", window.selectedPrice);
    localStorage.setItem("ticketType", window.selectedType);

    alert("เลือกบัตรสำเร็จ");

    location.href = "register.html";
}